server:
    port: 8070
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
   
env:
  spring.jpa.hibernate.ddl-auto: create-drop